/*++

Copyright (C) 2024 3MF Consortium (Original Author)

All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

This file has been generated by the Automatic Component Toolkit (ACT) version 1.8.1-develop.

Abstract: This is an autogenerated Java file in order to allow an easy
 use of the 3MF Library

Interface version: 2.4.0

*/

package lib3mf;

import com.sun.jna.Library;
import com.sun.jna.Memory;
import com.sun.jna.Native;
import com.sun.jna.Pointer;


import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.List;

public class BeamLatticeNode extends ImplicitNode {

	public BeamLatticeNode(Lib3MFWrapper wrapper, Pointer handle) {
		super(wrapper, handle);
	}

	/**
	 * Retrieves the input for the model resource id of the beam lattice
	 *
	 * @return the input port for the model resource id of the beam lattice (mesh with beamlattice extension)
	 * @throws Lib3MFException
	 */
	public ImplicitPort getInputBeamLattice() throws Lib3MFException {
		Pointer bufferBeamLattice = new Memory(8);
		mWrapper.checkError(this, mWrapper.lib3mf_beamlatticenode_getinputbeamlattice.invokeInt(new java.lang.Object[]{mHandle, bufferBeamLattice}));
		Pointer valueBeamLattice = bufferBeamLattice.getPointer(0);
		ImplicitPort beamLattice = null;
		if (valueBeamLattice == Pointer.NULL) {
		  throw new Lib3MFException(Lib3MFException.LIB3MF_ERROR_INVALIDPARAM, "BeamLattice was a null pointer");
		}
		beamLattice = mWrapper.PolymorphicFactory(valueBeamLattice, ImplicitPort.class);
		return beamLattice;
	}

	/**
	 * Retrieves the input for the position
	 *
	 * @return the input port for the position
	 * @throws Lib3MFException
	 */
	public ImplicitPort getInputPos() throws Lib3MFException {
		Pointer bufferPos = new Memory(8);
		mWrapper.checkError(this, mWrapper.lib3mf_beamlatticenode_getinputpos.invokeInt(new java.lang.Object[]{mHandle, bufferPos}));
		Pointer valuePos = bufferPos.getPointer(0);
		ImplicitPort pos = null;
		if (valuePos == Pointer.NULL) {
		  throw new Lib3MFException(Lib3MFException.LIB3MF_ERROR_INVALIDPARAM, "Pos was a null pointer");
		}
		pos = mWrapper.PolymorphicFactory(valuePos, ImplicitPort.class);
		return pos;
	}

	/**
	 * Retrieves the output
	 *
	 * @return the output port for the signed distance to the beam lattice
	 * @throws Lib3MFException
	 */
	public ImplicitPort getOutputDistance() throws Lib3MFException {
		Pointer bufferDistance = new Memory(8);
		mWrapper.checkError(this, mWrapper.lib3mf_beamlatticenode_getoutputdistance.invokeInt(new java.lang.Object[]{mHandle, bufferDistance}));
		Pointer valueDistance = bufferDistance.getPointer(0);
		ImplicitPort distance = null;
		if (valueDistance == Pointer.NULL) {
		  throw new Lib3MFException(Lib3MFException.LIB3MF_ERROR_INVALIDPARAM, "Distance was a null pointer");
		}
		distance = mWrapper.PolymorphicFactory(valueDistance, ImplicitPort.class);
		return distance;
	}

	/**
	 * Sets the accurate range for distance computation
	 *
	 * @param accurateRange the accurate range in model units
	 * @throws Lib3MFException
	 */
	public void setAccurateRange(double accurateRange) throws Lib3MFException {
		mWrapper.checkError(this, mWrapper.lib3mf_beamlatticenode_setaccuraterange.invokeInt(new java.lang.Object[]{mHandle, accurateRange}));
	}

	/**
	 * Retrieves the accurate range for distance computation
	 *
	 * @return the accurate range in model units
	 * @throws Lib3MFException
	 */
	public double getAccurateRange() throws Lib3MFException {
		Pointer bufferAccurateRange = new Memory(8);
		mWrapper.checkError(this, mWrapper.lib3mf_beamlatticenode_getaccuraterange.invokeInt(new java.lang.Object[]{mHandle, bufferAccurateRange}));
		return bufferAccurateRange.getDouble(0);
	}


}

