/*++

Copyright (C) 2024 3MF Consortium (Original Author)

All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

This file has been generated by the Automatic Component Toolkit (ACT) version 1.8.1-develop.

Abstract: This is an autogenerated Java file in order to allow an easy
 use of the 3MF Library

Interface version: 2.4.0

*/

package lib3mf;

import com.sun.jna.Library;
import com.sun.jna.Memory;
import com.sun.jna.Native;
import com.sun.jna.Pointer;


import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.List;

public class CustomXMLNode extends Base {

	public CustomXMLNode(Lib3MFWrapper wrapper, Pointer handle) {
		super(wrapper, handle);
	}

	/**
	 * Retrieves name of the node.
	 *
	 * @return returns the name of the node.
	 * @throws Lib3MFException
	 */
	public String getName() throws Lib3MFException {
		Pointer bytesNeededName = new Memory(4);
		mWrapper.checkError(this, mWrapper.lib3mf_customxmlnode_getname.invokeInt(new java.lang.Object[]{mHandle, 0, bytesNeededName, null}));
		int sizeName = bytesNeededName.getInt(0);
		Pointer bufferName = new Memory(sizeName);
		mWrapper.checkError(this, mWrapper.lib3mf_customxmlnode_getname.invokeInt(new java.lang.Object[]{mHandle, sizeName, bytesNeededName, bufferName}));
		return new String(bufferName.getByteArray(0, sizeName - 1), StandardCharsets.UTF_8);
	}

	/**
	 * Retrieves namespace of the node.
	 *
	 * @return returns the namespace of the node.
	 * @throws Lib3MFException
	 */
	public String getNameSpace() throws Lib3MFException {
		Pointer bytesNeededNameSpace = new Memory(4);
		mWrapper.checkError(this, mWrapper.lib3mf_customxmlnode_getnamespace.invokeInt(new java.lang.Object[]{mHandle, 0, bytesNeededNameSpace, null}));
		int sizeNameSpace = bytesNeededNameSpace.getInt(0);
		Pointer bufferNameSpace = new Memory(sizeNameSpace);
		mWrapper.checkError(this, mWrapper.lib3mf_customxmlnode_getnamespace.invokeInt(new java.lang.Object[]{mHandle, sizeNameSpace, bytesNeededNameSpace, bufferNameSpace}));
		return new String(bufferNameSpace.getByteArray(0, sizeNameSpace - 1), StandardCharsets.UTF_8);
	}

	/**
	 * Returns number of attributes.
	 *
	 * @return returns the number of attributes.
	 * @throws Lib3MFException
	 */
	public long getAttributeCount() throws Lib3MFException {
		Pointer bufferCount = new Memory(8);
		mWrapper.checkError(this, mWrapper.lib3mf_customxmlnode_getattributecount.invokeInt(new java.lang.Object[]{mHandle, bufferCount}));
		return bufferCount.getLong(0);
	}

	/**
	 * Returns attribute instance. Fails if Index is out of range.
	 *
	 * @param index Index of the attribute to return (0-based).
	 * @return XML Document attribute.
	 * @throws Lib3MFException
	 */
	public CustomXMLAttribute getAttribute(long index) throws Lib3MFException {
		Pointer bufferAttributeInstance = new Memory(8);
		mWrapper.checkError(this, mWrapper.lib3mf_customxmlnode_getattribute.invokeInt(new java.lang.Object[]{mHandle, index, bufferAttributeInstance}));
		Pointer valueAttributeInstance = bufferAttributeInstance.getPointer(0);
		CustomXMLAttribute attributeInstance = null;
		if (valueAttributeInstance == Pointer.NULL) {
		  throw new Lib3MFException(Lib3MFException.LIB3MF_ERROR_INVALIDPARAM, "AttributeInstance was a null pointer");
		}
		attributeInstance = mWrapper.PolymorphicFactory(valueAttributeInstance, CustomXMLAttribute.class);
		return attributeInstance;
	}

	/**
	 * Returns if attribute of a specific name exists.
	 *
	 * @param name Name of the attribute.
	 * @return Returns if the attribute exists.
	 * @throws Lib3MFException
	 */
	public boolean hasAttribute(String name) throws Lib3MFException {
		byte[] bytesName = name.getBytes(StandardCharsets.UTF_8);
		Memory bufferName = new Memory(bytesName.length + 1);
		bufferName.write(0, bytesName, 0, bytesName.length);
		bufferName.setByte(bytesName.length, (byte)0);
		Pointer bufferAttributeExists = new Memory(1);
		mWrapper.checkError(this, mWrapper.lib3mf_customxmlnode_hasattribute.invokeInt(new java.lang.Object[]{mHandle, bufferName, bufferAttributeExists}));
		return bufferAttributeExists.getByte(0) != 0;
	}

	/**
	 * Returns attribute instance of a specific name. 
	 *
	 * @param name Name of the attribute.
	 * @param mustExist If true, the call fails if attribute does not exist. If falls, the call will return null if the attribute does not exist.
	 * @return XML Document attribute.
	 * @throws Lib3MFException
	 */
	public CustomXMLAttribute findAttribute(String name, boolean mustExist) throws Lib3MFException {
		byte[] bytesName = name.getBytes(StandardCharsets.UTF_8);
		Memory bufferName = new Memory(bytesName.length + 1);
		bufferName.write(0, bytesName, 0, bytesName.length);
		bufferName.setByte(bytesName.length, (byte)0);
		Pointer bufferAttributeInstance = new Memory(8);
		mWrapper.checkError(this, mWrapper.lib3mf_customxmlnode_findattribute.invokeInt(new java.lang.Object[]{mHandle, bufferName, mustExist, bufferAttributeInstance}));
		Pointer valueAttributeInstance = bufferAttributeInstance.getPointer(0);
		CustomXMLAttribute attributeInstance = null;
		if (valueAttributeInstance != Pointer.NULL) {
		  attributeInstance = mWrapper.PolymorphicFactory(valueAttributeInstance, CustomXMLAttribute.class);
		}
		return attributeInstance;
	}

	/**
	 * Removes the attribute with a specific name. Does nothing if attribute does not exist.
	 *
	 * @param name Name of the attribute.
	 * @return Returns true if an attribute was removed.
	 * @throws Lib3MFException
	 */
	public boolean removeAttribute(String name) throws Lib3MFException {
		byte[] bytesName = name.getBytes(StandardCharsets.UTF_8);
		Memory bufferName = new Memory(bytesName.length + 1);
		bufferName.write(0, bytesName, 0, bytesName.length);
		bufferName.setByte(bytesName.length, (byte)0);
		Pointer bufferAttributeRemoved = new Memory(1);
		mWrapper.checkError(this, mWrapper.lib3mf_customxmlnode_removeattribute.invokeInt(new java.lang.Object[]{mHandle, bufferName, bufferAttributeRemoved}));
		return bufferAttributeRemoved.getByte(0) != 0;
	}

	/**
	 * Removes the attribute with a specific index. Fails if index is invalid
	 *
	 * @param index Index of the attribute to remove (0-based).
	 * @return Returns true if an attribute was removed.
	 * @throws Lib3MFException
	 */
	public boolean removeAttributeByIndex(long index) throws Lib3MFException {
		Pointer bufferAttributeRemoved = new Memory(1);
		mWrapper.checkError(this, mWrapper.lib3mf_customxmlnode_removeattributebyindex.invokeInt(new java.lang.Object[]{mHandle, index, bufferAttributeRemoved}));
		return bufferAttributeRemoved.getByte(0) != 0;
	}

	/**
	 * Adds an attribute with a specific name and string value. Fails if attribute already exists.
	 *
	 * @param name Name of the attribute.
	 * @param value Value of the attribute.
	 * @throws Lib3MFException
	 */
	public void addAttribute(String name, String value) throws Lib3MFException {
		byte[] bytesName = name.getBytes(StandardCharsets.UTF_8);
		Memory bufferName = new Memory(bytesName.length + 1);
		bufferName.write(0, bytesName, 0, bytesName.length);
		bufferName.setByte(bytesName.length, (byte)0);
		byte[] bytesValue = value.getBytes(StandardCharsets.UTF_8);
		Memory bufferValue = new Memory(bytesValue.length + 1);
		bufferValue.write(0, bytesValue, 0, bytesValue.length);
		bufferValue.setByte(bytesValue.length, (byte)0);
		mWrapper.checkError(this, mWrapper.lib3mf_customxmlnode_addattribute.invokeInt(new java.lang.Object[]{mHandle, bufferName, bufferValue}));
	}

	/**
	 * Adds an attribute with a specific name and integer value. Fails if attribute already exists.
	 *
	 * @param name Name of the attribute.
	 * @param value Value of the attribute.
	 * @throws Lib3MFException
	 */
	public void addIntegerAttribute(String name, long value) throws Lib3MFException {
		byte[] bytesName = name.getBytes(StandardCharsets.UTF_8);
		Memory bufferName = new Memory(bytesName.length + 1);
		bufferName.write(0, bytesName, 0, bytesName.length);
		bufferName.setByte(bytesName.length, (byte)0);
		mWrapper.checkError(this, mWrapper.lib3mf_customxmlnode_addintegerattribute.invokeInt(new java.lang.Object[]{mHandle, bufferName, value}));
	}

	/**
	 * Adds an attribute with a specific name and double value. Fails if attribute already exists.
	 *
	 * @param name Name of the attribute.
	 * @param value Value of the attribute.
	 * @throws Lib3MFException
	 */
	public void addDoubleAttribute(String name, double value) throws Lib3MFException {
		byte[] bytesName = name.getBytes(StandardCharsets.UTF_8);
		Memory bufferName = new Memory(bytesName.length + 1);
		bufferName.write(0, bytesName, 0, bytesName.length);
		bufferName.setByte(bytesName.length, (byte)0);
		mWrapper.checkError(this, mWrapper.lib3mf_customxmlnode_adddoubleattribute.invokeInt(new java.lang.Object[]{mHandle, bufferName, value}));
	}

	/**
	 * Adds an attribute with a specific name and bool value. Fails if attribute already exists.
	 *
	 * @param name Name of the attribute.
	 * @param value Value of the attribute.
	 * @throws Lib3MFException
	 */
	public void addBoolAttribute(String name, boolean value) throws Lib3MFException {
		byte[] bytesName = name.getBytes(StandardCharsets.UTF_8);
		Memory bufferName = new Memory(bytesName.length + 1);
		bufferName.write(0, bytesName, 0, bytesName.length);
		bufferName.setByte(bytesName.length, (byte)0);
		mWrapper.checkError(this, mWrapper.lib3mf_customxmlnode_addboolattribute.invokeInt(new java.lang.Object[]{mHandle, bufferName, value}));
	}

	/**
	 * Returns all the child nodes of the XML Node.
	 *
	 * @return returns the list of child nodes.
	 * @throws Lib3MFException
	 */
	public CustomXMLNodes getChildren() throws Lib3MFException {
		Pointer bufferChildNodes = new Memory(8);
		mWrapper.checkError(this, mWrapper.lib3mf_customxmlnode_getchildren.invokeInt(new java.lang.Object[]{mHandle, bufferChildNodes}));
		Pointer valueChildNodes = bufferChildNodes.getPointer(0);
		CustomXMLNodes childNodes = null;
		if (valueChildNodes == Pointer.NULL) {
		  throw new Lib3MFException(Lib3MFException.LIB3MF_ERROR_INVALIDPARAM, "ChildNodes was a null pointer");
		}
		childNodes = mWrapper.PolymorphicFactory(valueChildNodes, CustomXMLNodes.class);
		return childNodes;
	}

	/**
	 * Returns how many children of the XML Node have a specific name.
	 *
	 * @param name Name of the node.
	 * @return returns the number children with the specified name.
	 * @throws Lib3MFException
	 */
	public long countChildrenByName(String name) throws Lib3MFException {
		byte[] bytesName = name.getBytes(StandardCharsets.UTF_8);
		Memory bufferName = new Memory(bytesName.length + 1);
		bufferName.write(0, bytesName, 0, bytesName.length);
		bufferName.setByte(bytesName.length, (byte)0);
		Pointer bufferCount = new Memory(8);
		mWrapper.checkError(this, mWrapper.lib3mf_customxmlnode_countchildrenbyname.invokeInt(new java.lang.Object[]{mHandle, bufferName, bufferCount}));
		return bufferCount.getLong(0);
	}

	/**
	 * Returns all the child nodes of the XML Node with a specific name.
	 *
	 * @param name Name of the child.
	 * @return returns the list of child nodes.
	 * @throws Lib3MFException
	 */
	public CustomXMLNodes getChildrenByName(String name) throws Lib3MFException {
		byte[] bytesName = name.getBytes(StandardCharsets.UTF_8);
		Memory bufferName = new Memory(bytesName.length + 1);
		bufferName.write(0, bytesName, 0, bytesName.length);
		bufferName.setByte(bytesName.length, (byte)0);
		Pointer bufferChildNodes = new Memory(8);
		mWrapper.checkError(this, mWrapper.lib3mf_customxmlnode_getchildrenbyname.invokeInt(new java.lang.Object[]{mHandle, bufferName, bufferChildNodes}));
		Pointer valueChildNodes = bufferChildNodes.getPointer(0);
		CustomXMLNodes childNodes = null;
		if (valueChildNodes == Pointer.NULL) {
		  throw new Lib3MFException(Lib3MFException.LIB3MF_ERROR_INVALIDPARAM, "ChildNodes was a null pointer");
		}
		childNodes = mWrapper.PolymorphicFactory(valueChildNodes, CustomXMLNodes.class);
		return childNodes;
	}

	/**
	 * Returns if a child with a specific name exist.
	 *
	 * @param name Name of the child.
	 * @return returns if a child with a specific name exists.
	 * @throws Lib3MFException
	 */
	public boolean hasChild(String name) throws Lib3MFException {
		byte[] bytesName = name.getBytes(StandardCharsets.UTF_8);
		Memory bufferName = new Memory(bytesName.length + 1);
		bufferName.write(0, bytesName, 0, bytesName.length);
		bufferName.setByte(bytesName.length, (byte)0);
		Pointer bufferChildExists = new Memory(1);
		mWrapper.checkError(this, mWrapper.lib3mf_customxmlnode_haschild.invokeInt(new java.lang.Object[]{mHandle, bufferName, bufferChildExists}));
		return bufferChildExists.getByte(0) != 0;
	}

	/**
	 * Returns if a child with a specific name exist once and only once.
	 *
	 * @param name Name of the child.
	 * @return returns if a child with a specific name exists once and only once.
	 * @throws Lib3MFException
	 */
	public boolean hasUniqueChild(String name) throws Lib3MFException {
		byte[] bytesName = name.getBytes(StandardCharsets.UTF_8);
		Memory bufferName = new Memory(bytesName.length + 1);
		bufferName.write(0, bytesName, 0, bytesName.length);
		bufferName.setByte(bytesName.length, (byte)0);
		Pointer bufferChildExists = new Memory(1);
		mWrapper.checkError(this, mWrapper.lib3mf_customxmlnode_hasuniquechild.invokeInt(new java.lang.Object[]{mHandle, bufferName, bufferChildExists}));
		return bufferChildExists.getByte(0) != 0;
	}

	/**
	 * Returns child with a specific name. Throws an error if name does not exist once and only once.
	 *
	 * @param name Name of the child.
	 * @param mustExist If true, the call fails if child does not exist. If falls, the call will return null if the child does not exist.
	 * @return returns child instance or null.
	 * @throws Lib3MFException
	 */
	public CustomXMLNode findChild(String name, boolean mustExist) throws Lib3MFException {
		byte[] bytesName = name.getBytes(StandardCharsets.UTF_8);
		Memory bufferName = new Memory(bytesName.length + 1);
		bufferName.write(0, bytesName, 0, bytesName.length);
		bufferName.setByte(bytesName.length, (byte)0);
		Pointer bufferChildInstance = new Memory(8);
		mWrapper.checkError(this, mWrapper.lib3mf_customxmlnode_findchild.invokeInt(new java.lang.Object[]{mHandle, bufferName, mustExist, bufferChildInstance}));
		Pointer valueChildInstance = bufferChildInstance.getPointer(0);
		CustomXMLNode childInstance = null;
		if (valueChildInstance != Pointer.NULL) {
		  childInstance = mWrapper.PolymorphicFactory(valueChildInstance, CustomXMLNode.class);
		}
		return childInstance;
	}

	/**
	 * Adds a new child with a specific name.
	 *
	 * @param name Name of the child.
	 * @return returns child instance.
	 * @throws Lib3MFException
	 */
	public CustomXMLNode addChild(String name) throws Lib3MFException {
		byte[] bytesName = name.getBytes(StandardCharsets.UTF_8);
		Memory bufferName = new Memory(bytesName.length + 1);
		bufferName.write(0, bytesName, 0, bytesName.length);
		bufferName.setByte(bytesName.length, (byte)0);
		Pointer bufferChildInstance = new Memory(8);
		mWrapper.checkError(this, mWrapper.lib3mf_customxmlnode_addchild.invokeInt(new java.lang.Object[]{mHandle, bufferName, bufferChildInstance}));
		Pointer valueChildInstance = bufferChildInstance.getPointer(0);
		CustomXMLNode childInstance = null;
		if (valueChildInstance == Pointer.NULL) {
		  throw new Lib3MFException(Lib3MFException.LIB3MF_ERROR_INVALIDPARAM, "ChildInstance was a null pointer");
		}
		childInstance = mWrapper.PolymorphicFactory(valueChildInstance, CustomXMLNode.class);
		return childInstance;
	}

	/**
	 * Removes a specific child. All subsequent calls to the child will fail after the call.
	 *
	 * @param childInstance child instance to remove. Fails if given instance is not a child of the node.
	 * @throws Lib3MFException
	 */
	public void removeChild(CustomXMLNode childInstance) throws Lib3MFException {
		Pointer childInstanceHandle = null;
		if (childInstance != null) {
			childInstanceHandle = childInstance.getHandle();
		} else {
			throw new Lib3MFException(Lib3MFException.LIB3MF_ERROR_INVALIDPARAM, "ChildInstance is a null value.");
		}
		mWrapper.checkError(this, mWrapper.lib3mf_customxmlnode_removechild.invokeInt(new java.lang.Object[]{mHandle, childInstanceHandle}));
	}

	/**
	 * Removes all children with a specific name. Does nothing if no child with the name exists. All subsequent calls to the deleted children will fail after the call.
	 *
	 * @param name Name of the children.
	 * @return Returns how many children have been deleted.
	 * @throws Lib3MFException
	 */
	public long removeChildrenWithName(String name) throws Lib3MFException {
		byte[] bytesName = name.getBytes(StandardCharsets.UTF_8);
		Memory bufferName = new Memory(bytesName.length + 1);
		bufferName.write(0, bytesName, 0, bytesName.length);
		bufferName.setByte(bytesName.length, (byte)0);
		Pointer bufferNumberOfDeletedChildren = new Memory(8);
		mWrapper.checkError(this, mWrapper.lib3mf_customxmlnode_removechildrenwithname.invokeInt(new java.lang.Object[]{mHandle, bufferName, bufferNumberOfDeletedChildren}));
		return bufferNumberOfDeletedChildren.getLong(0);
	}

	/**
	 * Removes the node from its parent. The root node of the document can not be removed. Any subsequent call to the node fails after this.
	 *
	 * @throws Lib3MFException
	 */
	public void remove() throws Lib3MFException {
		mWrapper.checkError(this, mWrapper.lib3mf_customxmlnode_remove.invokeInt(new java.lang.Object[]{mHandle}));
	}


}

