/*++

Copyright (C) 2024 3MF Consortium (Original Author)

All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

This file has been generated by the Automatic Component Toolkit (ACT) version 1.8.1-develop.

Abstract: This is an autogenerated Java file in order to allow an easy
 use of the 3MF Library

Interface version: 2.6.0

*/

package lib3mf;

import com.sun.jna.Library;
import com.sun.jna.Memory;
import com.sun.jna.Native;
import com.sun.jna.Pointer;


import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.List;

public class DisplacementMeshObject extends MeshObject {

	public DisplacementMeshObject(Lib3MFWrapper wrapper, Pointer handle) {
		super(wrapper, handle);
	}

	/**
	 * Returns whether a triangle has displacement information assigned.
	 *
	 * @param index index of the triangle
	 * @return returns whether displacement information is assigned
	 * @throws Lib3MFException
	 */
	public boolean hasTriangleDisplacement(int index) throws Lib3MFException {
		Pointer bufferHasDisplacement = new Memory(1);
		mWrapper.checkError(this, mWrapper.lib3mf_displacementmeshobject_hastriangledisplacement.invokeInt(new java.lang.Object[]{mHandle, index, bufferHasDisplacement}));
		return bufferHasDisplacement.getByte(0) != 0;
	}

	/**
	 * Assigns a displacement group and coordinate indices to a triangle.
	 *
	 * @param index index of the triangle
	 * @param disp2DGroup displacement coordinate group used by the triangle
	 * @param displacement coordinate indices for the triangle vertices
	 * @throws Lib3MFException
	 */
	public void setTriangleDisplacement(int index, Disp2DGroup disp2DGroup, TriangleDisplacement displacement) throws Lib3MFException {
		Pointer disp2DGroupHandle = null;
		if (disp2DGroup != null) {
			disp2DGroupHandle = disp2DGroup.getHandle();
		} else {
			throw new Lib3MFException(Lib3MFException.LIB3MF_ERROR_INVALIDPARAM, "Disp2DGroup is a null value.");
		}
		Pointer bufferDisplacement = new Memory(TriangleDisplacement.SIZE);
		displacement.writeToPointer(bufferDisplacement, 0);
		mWrapper.checkError(this, mWrapper.lib3mf_displacementmeshobject_settriangledisplacement.invokeInt(new java.lang.Object[]{mHandle, index, disp2DGroupHandle, bufferDisplacement}));
	}

	/**
	 * Returns the displacement group and coordinate indices assigned to a triangle.
	 *
	 * @param index index of the triangle
	 * @return GetTriangleDisplacement Result Tuple
	 * @throws Lib3MFException
	 */
	public GetTriangleDisplacementResult getTriangleDisplacement(int index) throws Lib3MFException {
		Pointer bufferDisp2DGroup = new Memory(8);
		Pointer bufferDisplacement = new Memory(TriangleDisplacement.SIZE);
		mWrapper.checkError(this, mWrapper.lib3mf_displacementmeshobject_gettriangledisplacement.invokeInt(new java.lang.Object[]{mHandle, index, bufferDisp2DGroup, bufferDisplacement}));
		Pointer valueDisp2DGroup = bufferDisp2DGroup.getPointer(0);
		Disp2DGroup disp2DGroup = null;
		if (valueDisp2DGroup == Pointer.NULL) {
		  throw new Lib3MFException(Lib3MFException.LIB3MF_ERROR_INVALIDPARAM, "Disp2DGroup was a null pointer");
		}
		disp2DGroup = mWrapper.PolymorphicFactory(valueDisp2DGroup, Disp2DGroup.class);
		TriangleDisplacement displacement = new TriangleDisplacement();
		displacement.readFromPointer(bufferDisplacement, 0);
		GetTriangleDisplacementResult returnTuple = new GetTriangleDisplacementResult();
		returnTuple.Disp2DGroup = disp2DGroup;
		returnTuple.Displacement = displacement;
		return returnTuple;
	}

	public static class GetTriangleDisplacementResult {
		/**
		 * displacement coordinate group used by the triangle
		 */
		public Disp2DGroup Disp2DGroup;

		/**
		 * coordinate indices for the triangle vertices
		 */
		public TriangleDisplacement Displacement;

	}
	/**
	 * Removes displacement information from a triangle.
	 *
	 * @param index index of the triangle
	 * @throws Lib3MFException
	 */
	public void clearTriangleDisplacement(int index) throws Lib3MFException {
		mWrapper.checkError(this, mWrapper.lib3mf_displacementmeshobject_cleartriangledisplacement.invokeInt(new java.lang.Object[]{mHandle, index}));
	}


}

