/*++

Copyright (C) 2024 3MF Consortium (Original Author)

All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

This file has been generated by the Automatic Component Toolkit (ACT) version 1.8.1-develop.

Abstract: This is an autogenerated Java file in order to allow an easy
 use of the 3MF Library

Interface version: 2.6.0

*/

package lib3mf;

import com.sun.jna.Library;
import com.sun.jna.Memory;
import com.sun.jna.Native;
import com.sun.jna.Pointer;


import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.List;

public class Displacement2D extends Resource {

	public Displacement2D(Lib3MFWrapper wrapper, Pointer handle) {
		super(wrapper, handle);
	}

	/**
	 * Retrieves the PNG attachment used as displacement texture.
	 *
	 * @return attachment containing the displacement image
	 * @throws Lib3MFException
	 */
	public Attachment getAttachment() throws Lib3MFException {
		Pointer bufferAttachment = new Memory(8);
		mWrapper.checkError(this, mWrapper.lib3mf_displacement2d_getattachment.invokeInt(new java.lang.Object[]{mHandle, bufferAttachment}));
		Pointer valueAttachment = bufferAttachment.getPointer(0);
		Attachment attachment = null;
		if (valueAttachment == Pointer.NULL) {
		  throw new Lib3MFException(Lib3MFException.LIB3MF_ERROR_INVALIDPARAM, "Attachment was a null pointer");
		}
		attachment = mWrapper.PolymorphicFactory(valueAttachment, Attachment.class);
		return attachment;
	}

	/**
	 * Sets the PNG attachment used as displacement texture.
	 *
	 * @param attachment attachment containing the displacement image
	 * @throws Lib3MFException
	 */
	public void setAttachment(Attachment attachment) throws Lib3MFException {
		Pointer attachmentHandle = null;
		if (attachment != null) {
			attachmentHandle = attachment.getHandle();
		} else {
			throw new Lib3MFException(Lib3MFException.LIB3MF_ERROR_INVALIDPARAM, "Attachment is a null value.");
		}
		mWrapper.checkError(this, mWrapper.lib3mf_displacement2d_setattachment.invokeInt(new java.lang.Object[]{mHandle, attachmentHandle}));
	}

	/**
	 * Returns the image channel used for displacement values.
	 *
	 * @return selected image channel
	 * @throws Lib3MFException
	 */
	public Lib3MFWrapper.ChannelName getChannel() throws Lib3MFException {
		Pointer bufferChannel = new Memory(4);
		mWrapper.checkError(this, mWrapper.lib3mf_displacement2d_getchannel.invokeInt(new java.lang.Object[]{mHandle, bufferChannel}));
		return Lib3MFWrapper.EnumConversion.convertConstToChannelName(bufferChannel.getInt(0));
	}

	/**
	 * Sets the image channel used for displacement values.
	 *
	 * @param channel selected image channel
	 * @throws Lib3MFException
	 */
	public void setChannel(Lib3MFWrapper.ChannelName channel) throws Lib3MFException {
		mWrapper.checkError(this, mWrapper.lib3mf_displacement2d_setchannel.invokeInt(new java.lang.Object[]{mHandle, Lib3MFWrapper.EnumConversion.convertChannelNameToConst(channel)}));
	}

	/**
	 * Returns the displacement texture tile styles.
	 *
	 * @return GetTileStyleUV Result Tuple
	 * @throws Lib3MFException
	 */
	public GetTileStyleUVResult getTileStyleUV() throws Lib3MFException {
		Pointer bufferTileStyleU = new Memory(4);
		Pointer bufferTileStyleV = new Memory(4);
		mWrapper.checkError(this, mWrapper.lib3mf_displacement2d_gettilestyleuv.invokeInt(new java.lang.Object[]{mHandle, bufferTileStyleU, bufferTileStyleV}));
		GetTileStyleUVResult returnTuple = new GetTileStyleUVResult();
		returnTuple.TileStyleU = Lib3MFWrapper.EnumConversion.convertConstToTextureTileStyle(bufferTileStyleU.getInt(0));
		returnTuple.TileStyleV = Lib3MFWrapper.EnumConversion.convertConstToTextureTileStyle(bufferTileStyleV.getInt(0));
		return returnTuple;
	}

	public static class GetTileStyleUVResult {
		/**
		 * tile style in the u direction
		 */
		public Lib3MFWrapper.TextureTileStyle TileStyleU;

		/**
		 * tile style in the v direction
		 */
		public Lib3MFWrapper.TextureTileStyle TileStyleV;

	}
	/**
	 * Sets the displacement texture tile styles.
	 *
	 * @param tileStyleU tile style in the u direction
	 * @param tileStyleV tile style in the v direction
	 * @throws Lib3MFException
	 */
	public void setTileStyleUV(Lib3MFWrapper.TextureTileStyle tileStyleU, Lib3MFWrapper.TextureTileStyle tileStyleV) throws Lib3MFException {
		mWrapper.checkError(this, mWrapper.lib3mf_displacement2d_settilestyleuv.invokeInt(new java.lang.Object[]{mHandle, Lib3MFWrapper.EnumConversion.convertTextureTileStyleToConst(tileStyleU), Lib3MFWrapper.EnumConversion.convertTextureTileStyleToConst(tileStyleV)}));
	}

	/**
	 * Returns the displacement texture filter.
	 *
	 * @return selected texture filter
	 * @throws Lib3MFException
	 */
	public Lib3MFWrapper.TextureFilter getFilter() throws Lib3MFException {
		Pointer bufferFilter = new Memory(4);
		mWrapper.checkError(this, mWrapper.lib3mf_displacement2d_getfilter.invokeInt(new java.lang.Object[]{mHandle, bufferFilter}));
		return Lib3MFWrapper.EnumConversion.convertConstToTextureFilter(bufferFilter.getInt(0));
	}

	/**
	 * Sets the displacement texture filter.
	 *
	 * @param filter selected texture filter
	 * @throws Lib3MFException
	 */
	public void setFilter(Lib3MFWrapper.TextureFilter filter) throws Lib3MFException {
		mWrapper.checkError(this, mWrapper.lib3mf_displacement2d_setfilter.invokeInt(new java.lang.Object[]{mHandle, Lib3MFWrapper.EnumConversion.convertTextureFilterToConst(filter)}));
	}


}

