/*++

Copyright (C) 2024 3MF Consortium (Original Author)

All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

This file has been generated by the Automatic Component Toolkit (ACT) version 1.8.1-develop.

Abstract: This is an autogenerated Java file in order to allow an easy
 use of the 3MF Library

Interface version: 2.5.0

*/

package lib3mf;

import com.sun.jna.Memory;
import com.sun.jna.Pointer;

import java.util.Arrays;
import java.util.List;

public class Matrix4x4 {

	public double[][] Field = new double[4][4];

	public static final int SIZE = 128;

	public void readFromPointer(Pointer p, long offset) {
		Field[0][0] = p.getDouble(offset + 0);
		Field[0][1] = p.getDouble(offset + 8);
		Field[0][2] = p.getDouble(offset + 16);
		Field[0][3] = p.getDouble(offset + 24);
		Field[1][0] = p.getDouble(offset + 32);
		Field[1][1] = p.getDouble(offset + 40);
		Field[1][2] = p.getDouble(offset + 48);
		Field[1][3] = p.getDouble(offset + 56);
		Field[2][0] = p.getDouble(offset + 64);
		Field[2][1] = p.getDouble(offset + 72);
		Field[2][2] = p.getDouble(offset + 80);
		Field[2][3] = p.getDouble(offset + 88);
		Field[3][0] = p.getDouble(offset + 96);
		Field[3][1] = p.getDouble(offset + 104);
		Field[3][2] = p.getDouble(offset + 112);
		Field[3][3] = p.getDouble(offset + 120);
	}

	public void writeToPointer(Pointer p, long offset) {
		p.setDouble(offset + 0, Field[0][0]);
		p.setDouble(offset + 8, Field[0][1]);
		p.setDouble(offset + 16, Field[0][2]);
		p.setDouble(offset + 24, Field[0][3]);
		p.setDouble(offset + 32, Field[1][0]);
		p.setDouble(offset + 40, Field[1][1]);
		p.setDouble(offset + 48, Field[1][2]);
		p.setDouble(offset + 56, Field[1][3]);
		p.setDouble(offset + 64, Field[2][0]);
		p.setDouble(offset + 72, Field[2][1]);
		p.setDouble(offset + 80, Field[2][2]);
		p.setDouble(offset + 88, Field[2][3]);
		p.setDouble(offset + 96, Field[3][0]);
		p.setDouble(offset + 104, Field[3][1]);
		p.setDouble(offset + 112, Field[3][2]);
		p.setDouble(offset + 120, Field[3][3]);
	}

}

