# .readthedocs.yml - Configuration for MkDocs on Read the Docs

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"  # Python 3.9+ recommended for better compatibility

# Use MkDocs instead of Sphinx
mkdocs:
  configuration: DocumentationNew/mkdocs.yml  # Path to MkDocs config

# Enable additional output formats (optional, MkDocs natively supports HTML)
formats:
  - pdf
  - epub

python:
  install:
    - requirements: DocumentationNew/requirements.txt
