enable_testing()

if(USE_INCLUDED_SSL)
  set(LIBRESSL_APPS OFF CACHE BOOL "" FORCE)
  set(LIBRESSL_TESTS OFF CACHE BOOL "" FORCE)
  set(ENABLE_ASM OFF CACHE BOOL "" FORCE)
  set(LIBRESSL_SKIP_INSTALL ON CACHE BOOL "" FORCE)
  add_subdirectory(../Libraries/libressl ${CMAKE_CURRENT_BINARY_DIR}/libressl EXCLUDE_FROM_ALL)
  set_target_properties(ssl PROPERTIES FOLDER LibreSSL)
  set_target_properties(crypto PROPERTIES FOLDER LibreSSL)
  set_target_properties(ssl_obj PROPERTIES FOLDER LibreSSL)
  set_target_properties(crypto_obj PROPERTIES FOLDER LibreSSL)
endif()

file(MAKE_DIRECTORY ${PROJECT_BINARY_DIR}/Writer)
file(MAKE_DIRECTORY ${PROJECT_BINARY_DIR}/SecureContent)

set(LIB3MF_TESTFILESPATH "${CMAKE_CURRENT_SOURCE_DIR}/TestFiles/" CACHE INTERNAL "")
set(LIB3MF_OUTFILESPATH "${PROJECT_BINARY_DIR}/" CACHE INTERNAL "")
set(LIB3MF_TESTFILESPATH "${LIB3MF_TESTFILESPATH}" PARENT_SCOPE)
set(LIB3MF_OUTFILESPATH "${LIB3MF_OUTFILESPATH}" PARENT_SCOPE)

# Test the CPP-Bindings of the library
add_subdirectory(CPP_Bindings)

set(STARTUPPROJECT ${STARTUPPROJECT} PARENT_SCOPE)
