/*++

Copyright (C) 2024 3MF Consortium (Original Author)

All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

This file has been generated by the Automatic Component Toolkit (ACT) version 1.8.1-develop.

Abstract: This is an autogenerated Java file in order to allow an easy
 use of the 3MF Library

Interface version: 2.6.0

*/

package lib3mf;

import com.sun.jna.Library;
import com.sun.jna.Memory;
import com.sun.jna.Native;
import com.sun.jna.Pointer;
import java.lang.ref.Cleaner;


import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.List;

public class AccessRight extends Base {

	public AccessRight(Lib3MFWrapper wrapper, Pointer handle) {
		super(wrapper, handle);
	}

	/**
	 * Gets the consumer associated with this access right
	 *
	 * @return The consumer instance
	 * @throws Lib3MFException
	 */
	public Consumer getConsumer() throws Lib3MFException {
		Pointer bufferConsumer = new Memory(8);
		mWrapper.checkError(this, mWrapper.lib3mf_accessright_getconsumer.invokeInt(new java.lang.Object[]{mHandle, bufferConsumer}));
		Pointer valueConsumer = bufferConsumer.getPointer(0);
		Consumer consumer = null;
		if (valueConsumer == Pointer.NULL) {
		  throw new Lib3MFException(Lib3MFException.LIB3MF_ERROR_INVALIDPARAM, "Consumer was a null pointer");
		}
		consumer = mWrapper.PolymorphicFactory(valueConsumer, Consumer.class);
		return consumer;
	}

	/**
	 * Gets the associated encryption algorithm
	 *
	 * @return The algorithm used for the key in this accessright
	 * @throws Lib3MFException
	 */
	public Lib3MFWrapper.WrappingAlgorithm getWrappingAlgorithm() throws Lib3MFException {
		Pointer bufferAlgorithm = new Memory(4);
		mWrapper.checkError(this, mWrapper.lib3mf_accessright_getwrappingalgorithm.invokeInt(new java.lang.Object[]{mHandle, bufferAlgorithm}));
		return Lib3MFWrapper.EnumConversion.convertConstToWrappingAlgorithm(bufferAlgorithm.getInt(0));
	}

	/**
	 * Gets the associated mask generation function algorithm
	 *
	 * @return The MFG1 algorithm
	 * @throws Lib3MFException
	 */
	public Lib3MFWrapper.MgfAlgorithm getMgfAlgorithm() throws Lib3MFException {
		Pointer bufferAlgorithm = new Memory(4);
		mWrapper.checkError(this, mWrapper.lib3mf_accessright_getmgfalgorithm.invokeInt(new java.lang.Object[]{mHandle, bufferAlgorithm}));
		return Lib3MFWrapper.EnumConversion.convertConstToMgfAlgorithm(bufferAlgorithm.getInt(0));
	}

	/**
	 * Gets the digest method assoicated
	 *
	 * @return The digest method for this accessright
	 * @throws Lib3MFException
	 */
	public Lib3MFWrapper.DigestMethod getDigestMethod() throws Lib3MFException {
		Pointer bufferAlgorithm = new Memory(4);
		mWrapper.checkError(this, mWrapper.lib3mf_accessright_getdigestmethod.invokeInt(new java.lang.Object[]{mHandle, bufferAlgorithm}));
		return Lib3MFWrapper.EnumConversion.convertConstToDigestMethod(bufferAlgorithm.getInt(0));
	}


}

