/*++

Copyright (C) 2024 3MF Consortium (Original Author)

All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

This file has been generated by the Automatic Component Toolkit (ACT) version 1.8.1-develop.

Abstract: This is an autogenerated Java file in order to allow an easy
 use of the 3MF Library

Interface version: 2.4.0

*/

package lib3mf;

import com.sun.jna.Library;
import com.sun.jna.Memory;
import com.sun.jna.Native;
import com.sun.jna.Pointer;
import java.lang.ref.Cleaner;


import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.List;

public class BinaryStream extends Base {

	public BinaryStream(Lib3MFWrapper wrapper, Pointer handle) {
		super(wrapper, handle);
	}

	/**
	 * Retrieves an binary streams package path for the binary data.
	 *
	 * @return binary streams package binary path.
	 * @throws Lib3MFException
	 */
	public String getBinaryPath() throws Lib3MFException {
		Pointer bytesNeededPath = new Memory(4);
		mWrapper.checkError(this, mWrapper.lib3mf_binarystream_getbinarypath.invokeInt(new java.lang.Object[]{mHandle, 0, bytesNeededPath, null}));
		int sizePath = bytesNeededPath.getInt(0);
		Pointer bufferPath = new Memory(sizePath);
		mWrapper.checkError(this, mWrapper.lib3mf_binarystream_getbinarypath.invokeInt(new java.lang.Object[]{mHandle, sizePath, bytesNeededPath, bufferPath}));
		return new String(bufferPath.getByteArray(0, sizePath - 1), StandardCharsets.UTF_8);
	}

	/**
	 * Retrieves an binary streams package path for the index data.
	 *
	 * @return binary streams package index path.
	 * @throws Lib3MFException
	 */
	public String getIndexPath() throws Lib3MFException {
		Pointer bytesNeededPath = new Memory(4);
		mWrapper.checkError(this, mWrapper.lib3mf_binarystream_getindexpath.invokeInt(new java.lang.Object[]{mHandle, 0, bytesNeededPath, null}));
		int sizePath = bytesNeededPath.getInt(0);
		Pointer bufferPath = new Memory(sizePath);
		mWrapper.checkError(this, mWrapper.lib3mf_binarystream_getindexpath.invokeInt(new java.lang.Object[]{mHandle, sizePath, bytesNeededPath, bufferPath}));
		return new String(bufferPath.getByteArray(0, sizePath - 1), StandardCharsets.UTF_8);
	}

	/**
	 * Retrieves an binary streams uuid.
	 *
	 * @return binary streams uuid
	 * @throws Lib3MFException
	 */
	public String getUUID() throws Lib3MFException {
		Pointer bytesNeededUUID = new Memory(4);
		mWrapper.checkError(this, mWrapper.lib3mf_binarystream_getuuid.invokeInt(new java.lang.Object[]{mHandle, 0, bytesNeededUUID, null}));
		int sizeUUID = bytesNeededUUID.getInt(0);
		Pointer bufferUUID = new Memory(sizeUUID);
		mWrapper.checkError(this, mWrapper.lib3mf_binarystream_getuuid.invokeInt(new java.lang.Object[]{mHandle, sizeUUID, bytesNeededUUID, bufferUUID}));
		return new String(bufferUUID.getByteArray(0, sizeUUID - 1), StandardCharsets.UTF_8);
	}

	/**
	 * Sets the float compression mode to raw. All subsequent writes will adhere to this mode.
	 *
	 * @throws Lib3MFException
	 */
	public void disableDiscretizedArrayCompression() throws Lib3MFException {
		mWrapper.checkError(this, mWrapper.lib3mf_binarystream_disablediscretizedarraycompression.invokeInt(new java.lang.Object[]{mHandle}));
	}

	/**
	 * Sets the compression mode to a quantized array. All subsequent writes will adhere to this mode.
	 *
	 * @param units Unit factor to use for quantization.
	 * @param predictionType Prediction type to use for arrays.
	 * @throws Lib3MFException
	 */
	public void enableDiscretizedArrayCompression(double units, Lib3MFWrapper.BinaryStreamPredictionType predictionType) throws Lib3MFException {
		mWrapper.checkError(this, mWrapper.lib3mf_binarystream_enablediscretizedarraycompression.invokeInt(new java.lang.Object[]{mHandle, units, Lib3MFWrapper.EnumConversion.convertBinaryStreamPredictionTypeToConst(predictionType)}));
	}

	/**
	 * Switches to fast LZ4 compression mode.
	 *
	 * @param compressionLevel Compression level (2-12).
	 * @throws Lib3MFException
	 */
	public void enableLZ4(int compressionLevel) throws Lib3MFException {
		mWrapper.checkError(this, mWrapper.lib3mf_binarystream_enablelz4.invokeInt(new java.lang.Object[]{mHandle, compressionLevel}));
	}

	/**
	 * Switches to ZLib compression mode.
	 *
	 * @param compressionLevel Compression level (0-9).
	 * @throws Lib3MFException
	 */
	public void enableZLib(int compressionLevel) throws Lib3MFException {
		mWrapper.checkError(this, mWrapper.lib3mf_binarystream_enablezlib.invokeInt(new java.lang.Object[]{mHandle, compressionLevel}));
	}

	/**
	 * Switches to ZStd compression mode.
	 *
	 * @param compressionLevel Compression level.
	 * @throws Lib3MFException
	 */
	public void enableZstd(int compressionLevel) throws Lib3MFException {
		mWrapper.checkError(this, mWrapper.lib3mf_binarystream_enablezstd.invokeInt(new java.lang.Object[]{mHandle, compressionLevel}));
	}


}

