/*++

Copyright (C) 2024 3MF Consortium (Original Author)

All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

This file has been generated by the Automatic Component Toolkit (ACT) version 1.8.1-develop.

Abstract: This is an autogenerated Java file in order to allow an easy
 use of the 3MF Library

Interface version: 2.4.0

*/

package lib3mf;

import com.sun.jna.Library;
import com.sun.jna.Memory;
import com.sun.jna.Native;
import com.sun.jna.Pointer;
import java.lang.ref.Cleaner;


import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.List;

public class ToolpathProfile extends Base {

	public ToolpathProfile(Lib3MFWrapper wrapper, Pointer handle) {
		super(wrapper, handle);
	}

	/**
	 * Retrieves the profile's uuid
	 *
	 * @return Returns the uuid value.
	 * @throws Lib3MFException
	 */
	public String getUUID() throws Lib3MFException {
		Pointer bytesNeededUUID = new Memory(4);
		mWrapper.checkError(this, mWrapper.lib3mf_toolpathprofile_getuuid.invokeInt(new java.lang.Object[]{mHandle, 0, bytesNeededUUID, null}));
		int sizeUUID = bytesNeededUUID.getInt(0);
		Pointer bufferUUID = new Memory(sizeUUID);
		mWrapper.checkError(this, mWrapper.lib3mf_toolpathprofile_getuuid.invokeInt(new java.lang.Object[]{mHandle, sizeUUID, bytesNeededUUID, bufferUUID}));
		return new String(bufferUUID.getByteArray(0, sizeUUID - 1), StandardCharsets.UTF_8);
	}

	/**
	 * Retrieves the profile's name
	 *
	 * @return Returns the name.
	 * @throws Lib3MFException
	 */
	public String getName() throws Lib3MFException {
		Pointer bytesNeededName = new Memory(4);
		mWrapper.checkError(this, mWrapper.lib3mf_toolpathprofile_getname.invokeInt(new java.lang.Object[]{mHandle, 0, bytesNeededName, null}));
		int sizeName = bytesNeededName.getInt(0);
		Pointer bufferName = new Memory(sizeName);
		mWrapper.checkError(this, mWrapper.lib3mf_toolpathprofile_getname.invokeInt(new java.lang.Object[]{mHandle, sizeName, bytesNeededName, bufferName}));
		return new String(bufferName.getByteArray(0, sizeName - 1), StandardCharsets.UTF_8);
	}

	/**
	 * Returns the number of parameters.
	 *
	 * @return Returns the number of parameters.
	 * @throws Lib3MFException
	 */
	public int getParameterCount() throws Lib3MFException {
		Pointer bufferCount = new Memory(4);
		mWrapper.checkError(this, mWrapper.lib3mf_toolpathprofile_getparametercount.invokeInt(new java.lang.Object[]{mHandle, bufferCount}));
		return bufferCount.getInt(0);
	}

	/**
	 * Returns the Name of a parameter.
	 *
	 * @param index Index of Parameter (0-based). Call will fail if an invalid index is given.
	 * @return Returns the name of the parameter.
	 * @throws Lib3MFException
	 */
	public String getParameterName(int index) throws Lib3MFException {
		Pointer bytesNeededName = new Memory(4);
		mWrapper.checkError(this, mWrapper.lib3mf_toolpathprofile_getparametername.invokeInt(new java.lang.Object[]{mHandle, index, 0, bytesNeededName, null}));
		int sizeName = bytesNeededName.getInt(0);
		Pointer bufferName = new Memory(sizeName);
		mWrapper.checkError(this, mWrapper.lib3mf_toolpathprofile_getparametername.invokeInt(new java.lang.Object[]{mHandle, index, sizeName, bytesNeededName, bufferName}));
		return new String(bufferName.getByteArray(0, sizeName - 1), StandardCharsets.UTF_8);
	}

	/**
	 * Returns the NameSpace of a parameter.
	 *
	 * @param index Index of Parameter (0-based). Call will fail if an invalid index is given.
	 * @return Returns the namespace of the parameter.
	 * @throws Lib3MFException
	 */
	public String getParameterNameSpace(int index) throws Lib3MFException {
		Pointer bytesNeededNameSpace = new Memory(4);
		mWrapper.checkError(this, mWrapper.lib3mf_toolpathprofile_getparameternamespace.invokeInt(new java.lang.Object[]{mHandle, index, 0, bytesNeededNameSpace, null}));
		int sizeNameSpace = bytesNeededNameSpace.getInt(0);
		Pointer bufferNameSpace = new Memory(sizeNameSpace);
		mWrapper.checkError(this, mWrapper.lib3mf_toolpathprofile_getparameternamespace.invokeInt(new java.lang.Object[]{mHandle, index, sizeNameSpace, bytesNeededNameSpace, bufferNameSpace}));
		return new String(bufferNameSpace.getByteArray(0, sizeNameSpace - 1), StandardCharsets.UTF_8);
	}

	/**
	 * Checks if a parameter value exists.
	 *
	 * @param nameSpaceName Name of the Parameter Namespace.
	 * @param valueName Value key string.
	 * @return Returns if a value exists.
	 * @throws Lib3MFException
	 */
	public boolean hasParameterValue(String nameSpaceName, String valueName) throws Lib3MFException {
		byte[] bytesNameSpaceName = nameSpaceName.getBytes(StandardCharsets.UTF_8);
		Memory bufferNameSpaceName = new Memory(bytesNameSpaceName.length + 1);
		bufferNameSpaceName.write(0, bytesNameSpaceName, 0, bytesNameSpaceName.length);
		bufferNameSpaceName.setByte(bytesNameSpaceName.length, (byte)0);
		byte[] bytesValueName = valueName.getBytes(StandardCharsets.UTF_8);
		Memory bufferValueName = new Memory(bytesValueName.length + 1);
		bufferValueName.write(0, bytesValueName, 0, bytesValueName.length);
		bufferValueName.setByte(bytesValueName.length, (byte)0);
		Pointer bufferValueExists = new Memory(1);
		mWrapper.checkError(this, mWrapper.lib3mf_toolpathprofile_hasparametervalue.invokeInt(new java.lang.Object[]{mHandle, bufferNameSpaceName, bufferValueName, bufferValueExists}));
		return bufferValueExists.getByte(0) != 0;
	}

	/**
	 * Retrieves a profile's base parameter value without modifier. Fails if value does not exist.
	 *
	 * @param nameSpaceName Name of the Parameter Namespace.
	 * @param valueName Value key string.
	 * @return Returns the base value of the parameter.
	 * @throws Lib3MFException
	 */
	public String getParameterValue(String nameSpaceName, String valueName) throws Lib3MFException {
		byte[] bytesNameSpaceName = nameSpaceName.getBytes(StandardCharsets.UTF_8);
		Memory bufferNameSpaceName = new Memory(bytesNameSpaceName.length + 1);
		bufferNameSpaceName.write(0, bytesNameSpaceName, 0, bytesNameSpaceName.length);
		bufferNameSpaceName.setByte(bytesNameSpaceName.length, (byte)0);
		byte[] bytesValueName = valueName.getBytes(StandardCharsets.UTF_8);
		Memory bufferValueName = new Memory(bytesValueName.length + 1);
		bufferValueName.write(0, bytesValueName, 0, bytesValueName.length);
		bufferValueName.setByte(bytesValueName.length, (byte)0);
		Pointer bytesNeededValue = new Memory(4);
		mWrapper.checkError(this, mWrapper.lib3mf_toolpathprofile_getparametervalue.invokeInt(new java.lang.Object[]{mHandle, bufferNameSpaceName, bufferValueName, 0, bytesNeededValue, null}));
		int sizeValue = bytesNeededValue.getInt(0);
		Pointer bufferValue = new Memory(sizeValue);
		mWrapper.checkError(this, mWrapper.lib3mf_toolpathprofile_getparametervalue.invokeInt(new java.lang.Object[]{mHandle, bufferNameSpaceName, bufferValueName, sizeValue, bytesNeededValue, bufferValue}));
		return new String(bufferValue.getByteArray(0, sizeValue - 1), StandardCharsets.UTF_8);
	}

	/**
	 * Retrieves a profile's base parameter value without modifier
	 *
	 * @param nameSpaceName Name of the Parameter Namespace.
	 * @param valueName Value key string.
	 * @param defaultValue Default value if value does not exist.
	 * @return Returns the base value of the parameter.
	 * @throws Lib3MFException
	 */
	public String getParameterValueDef(String nameSpaceName, String valueName, String defaultValue) throws Lib3MFException {
		byte[] bytesNameSpaceName = nameSpaceName.getBytes(StandardCharsets.UTF_8);
		Memory bufferNameSpaceName = new Memory(bytesNameSpaceName.length + 1);
		bufferNameSpaceName.write(0, bytesNameSpaceName, 0, bytesNameSpaceName.length);
		bufferNameSpaceName.setByte(bytesNameSpaceName.length, (byte)0);
		byte[] bytesValueName = valueName.getBytes(StandardCharsets.UTF_8);
		Memory bufferValueName = new Memory(bytesValueName.length + 1);
		bufferValueName.write(0, bytesValueName, 0, bytesValueName.length);
		bufferValueName.setByte(bytesValueName.length, (byte)0);
		byte[] bytesDefaultValue = defaultValue.getBytes(StandardCharsets.UTF_8);
		Memory bufferDefaultValue = new Memory(bytesDefaultValue.length + 1);
		bufferDefaultValue.write(0, bytesDefaultValue, 0, bytesDefaultValue.length);
		bufferDefaultValue.setByte(bytesDefaultValue.length, (byte)0);
		Pointer bytesNeededValue = new Memory(4);
		mWrapper.checkError(this, mWrapper.lib3mf_toolpathprofile_getparametervaluedef.invokeInt(new java.lang.Object[]{mHandle, bufferNameSpaceName, bufferValueName, bufferDefaultValue, 0, bytesNeededValue, null}));
		int sizeValue = bytesNeededValue.getInt(0);
		Pointer bufferValue = new Memory(sizeValue);
		mWrapper.checkError(this, mWrapper.lib3mf_toolpathprofile_getparametervaluedef.invokeInt(new java.lang.Object[]{mHandle, bufferNameSpaceName, bufferValueName, bufferDefaultValue, sizeValue, bytesNeededValue, bufferValue}));
		return new String(bufferValue.getByteArray(0, sizeValue - 1), StandardCharsets.UTF_8);
	}

	/**
	 * Retrieves a profile's base parameter value as double without modifier. Fails if value does not exist or is not a double value.
	 *
	 * @param nameSpaceName Name of the Parameter Namespace.
	 * @param valueName Value key string.
	 * @return Returns the base value of the parameter.
	 * @throws Lib3MFException
	 */
	public double getParameterDoubleValue(String nameSpaceName, String valueName) throws Lib3MFException {
		byte[] bytesNameSpaceName = nameSpaceName.getBytes(StandardCharsets.UTF_8);
		Memory bufferNameSpaceName = new Memory(bytesNameSpaceName.length + 1);
		bufferNameSpaceName.write(0, bytesNameSpaceName, 0, bytesNameSpaceName.length);
		bufferNameSpaceName.setByte(bytesNameSpaceName.length, (byte)0);
		byte[] bytesValueName = valueName.getBytes(StandardCharsets.UTF_8);
		Memory bufferValueName = new Memory(bytesValueName.length + 1);
		bufferValueName.write(0, bytesValueName, 0, bytesValueName.length);
		bufferValueName.setByte(bytesValueName.length, (byte)0);
		Pointer bufferValue = new Memory(8);
		mWrapper.checkError(this, mWrapper.lib3mf_toolpathprofile_getparameterdoublevalue.invokeInt(new java.lang.Object[]{mHandle, bufferNameSpaceName, bufferValueName, bufferValue}));
		return bufferValue.getDouble(0);
	}

	/**
	 * Retrieves a profile's base parameter value as double without modifier.
	 *
	 * @param nameSpaceName Name of the Parameter Namespace.
	 * @param valueName Value key string.
	 * @param defaultValue Default value if value does not exist or is not a double value.
	 * @return Returns the base value of the parameter.
	 * @throws Lib3MFException
	 */
	public double getParameterDoubleValueDef(String nameSpaceName, String valueName, double defaultValue) throws Lib3MFException {
		byte[] bytesNameSpaceName = nameSpaceName.getBytes(StandardCharsets.UTF_8);
		Memory bufferNameSpaceName = new Memory(bytesNameSpaceName.length + 1);
		bufferNameSpaceName.write(0, bytesNameSpaceName, 0, bytesNameSpaceName.length);
		bufferNameSpaceName.setByte(bytesNameSpaceName.length, (byte)0);
		byte[] bytesValueName = valueName.getBytes(StandardCharsets.UTF_8);
		Memory bufferValueName = new Memory(bytesValueName.length + 1);
		bufferValueName.write(0, bytesValueName, 0, bytesValueName.length);
		bufferValueName.setByte(bytesValueName.length, (byte)0);
		Pointer bufferValue = new Memory(8);
		mWrapper.checkError(this, mWrapper.lib3mf_toolpathprofile_getparameterdoublevaluedef.invokeInt(new java.lang.Object[]{mHandle, bufferNameSpaceName, bufferValueName, defaultValue, bufferValue}));
		return bufferValue.getDouble(0);
	}

	/**
	 * Retrieves a profile's base parameter value as integer without modifier. Fails if value does not exist or is not a integer value.
	 *
	 * @param nameSpaceName Name of the Parameter Namespace.
	 * @param valueName Value key string.
	 * @return Returns the base value of the parameter.
	 * @throws Lib3MFException
	 */
	public long getParameterIntegerValue(String nameSpaceName, String valueName) throws Lib3MFException {
		byte[] bytesNameSpaceName = nameSpaceName.getBytes(StandardCharsets.UTF_8);
		Memory bufferNameSpaceName = new Memory(bytesNameSpaceName.length + 1);
		bufferNameSpaceName.write(0, bytesNameSpaceName, 0, bytesNameSpaceName.length);
		bufferNameSpaceName.setByte(bytesNameSpaceName.length, (byte)0);
		byte[] bytesValueName = valueName.getBytes(StandardCharsets.UTF_8);
		Memory bufferValueName = new Memory(bytesValueName.length + 1);
		bufferValueName.write(0, bytesValueName, 0, bytesValueName.length);
		bufferValueName.setByte(bytesValueName.length, (byte)0);
		Pointer bufferValue = new Memory(8);
		mWrapper.checkError(this, mWrapper.lib3mf_toolpathprofile_getparameterintegervalue.invokeInt(new java.lang.Object[]{mHandle, bufferNameSpaceName, bufferValueName, bufferValue}));
		return bufferValue.getLong(0);
	}

	/**
	 * Retrieves a profile's base parameter value as integer without modifier .
	 *
	 * @param nameSpaceName Name of the Parameter Namespace.
	 * @param valueName Value key string.
	 * @param defaultValue Default value if value does not exist or is not a integer value.
	 * @return Returns the base value of the parameter.
	 * @throws Lib3MFException
	 */
	public long getParameterIntegerValueDef(String nameSpaceName, String valueName, long defaultValue) throws Lib3MFException {
		byte[] bytesNameSpaceName = nameSpaceName.getBytes(StandardCharsets.UTF_8);
		Memory bufferNameSpaceName = new Memory(bytesNameSpaceName.length + 1);
		bufferNameSpaceName.write(0, bytesNameSpaceName, 0, bytesNameSpaceName.length);
		bufferNameSpaceName.setByte(bytesNameSpaceName.length, (byte)0);
		byte[] bytesValueName = valueName.getBytes(StandardCharsets.UTF_8);
		Memory bufferValueName = new Memory(bytesValueName.length + 1);
		bufferValueName.write(0, bytesValueName, 0, bytesValueName.length);
		bufferValueName.setByte(bytesValueName.length, (byte)0);
		Pointer bufferValue = new Memory(8);
		mWrapper.checkError(this, mWrapper.lib3mf_toolpathprofile_getparameterintegervaluedef.invokeInt(new java.lang.Object[]{mHandle, bufferNameSpaceName, bufferValueName, defaultValue, bufferValue}));
		return bufferValue.getLong(0);
	}

	/**
	 * Retrieves a profile's base parameter value as boolean without modifier. Fails if value does not exist or is not a boolean value.
	 *
	 * @param nameSpaceName Name of the Parameter Namespace.
	 * @param valueName Value key string.
	 * @return Returns the base value of the parameter.
	 * @throws Lib3MFException
	 */
	public boolean getParameterBoolValue(String nameSpaceName, String valueName) throws Lib3MFException {
		byte[] bytesNameSpaceName = nameSpaceName.getBytes(StandardCharsets.UTF_8);
		Memory bufferNameSpaceName = new Memory(bytesNameSpaceName.length + 1);
		bufferNameSpaceName.write(0, bytesNameSpaceName, 0, bytesNameSpaceName.length);
		bufferNameSpaceName.setByte(bytesNameSpaceName.length, (byte)0);
		byte[] bytesValueName = valueName.getBytes(StandardCharsets.UTF_8);
		Memory bufferValueName = new Memory(bytesValueName.length + 1);
		bufferValueName.write(0, bytesValueName, 0, bytesValueName.length);
		bufferValueName.setByte(bytesValueName.length, (byte)0);
		Pointer bufferValue = new Memory(1);
		mWrapper.checkError(this, mWrapper.lib3mf_toolpathprofile_getparameterboolvalue.invokeInt(new java.lang.Object[]{mHandle, bufferNameSpaceName, bufferValueName, bufferValue}));
		return bufferValue.getByte(0) != 0;
	}

	/**
	 * Retrieves a profile's base parameter value as boolean without modifier.
	 *
	 * @param nameSpaceName Name of the Parameter Namespace.
	 * @param valueName Value key string.
	 * @param defaultValue Default value if value does not exist or is not a boolean value.
	 * @return Returns the base value of the parameter.
	 * @throws Lib3MFException
	 */
	public boolean getParameterBoolValueDef(String nameSpaceName, String valueName, boolean defaultValue) throws Lib3MFException {
		byte[] bytesNameSpaceName = nameSpaceName.getBytes(StandardCharsets.UTF_8);
		Memory bufferNameSpaceName = new Memory(bytesNameSpaceName.length + 1);
		bufferNameSpaceName.write(0, bytesNameSpaceName, 0, bytesNameSpaceName.length);
		bufferNameSpaceName.setByte(bytesNameSpaceName.length, (byte)0);
		byte[] bytesValueName = valueName.getBytes(StandardCharsets.UTF_8);
		Memory bufferValueName = new Memory(bytesValueName.length + 1);
		bufferValueName.write(0, bytesValueName, 0, bytesValueName.length);
		bufferValueName.setByte(bytesValueName.length, (byte)0);
		Pointer bufferValue = new Memory(1);
		mWrapper.checkError(this, mWrapper.lib3mf_toolpathprofile_getparameterboolvaluedef.invokeInt(new java.lang.Object[]{mHandle, bufferNameSpaceName, bufferValueName, defaultValue, bufferValue}));
		return bufferValue.getByte(0) != 0;
	}

	/**
	 * Sets the profile's name
	 *
	 * @param name Returns the name.
	 * @throws Lib3MFException
	 */
	public void setName(String name) throws Lib3MFException {
		byte[] bytesName = name.getBytes(StandardCharsets.UTF_8);
		Memory bufferName = new Memory(bytesName.length + 1);
		bufferName.write(0, bytesName, 0, bytesName.length);
		bufferName.setByte(bytesName.length, (byte)0);
		mWrapper.checkError(this, mWrapper.lib3mf_toolpathprofile_setname.invokeInt(new java.lang.Object[]{mHandle, bufferName}));
	}

	/**
	 * Sets a profile's base parameter value. Fails, if parameter already exists.
	 *
	 * @param nameSpaceName Name of the Parameter Namespace.
	 * @param valueName Value key string.
	 * @param value String value of the parameter.
	 * @throws Lib3MFException
	 */
	public void setParameterValue(String nameSpaceName, String valueName, String value) throws Lib3MFException {
		byte[] bytesNameSpaceName = nameSpaceName.getBytes(StandardCharsets.UTF_8);
		Memory bufferNameSpaceName = new Memory(bytesNameSpaceName.length + 1);
		bufferNameSpaceName.write(0, bytesNameSpaceName, 0, bytesNameSpaceName.length);
		bufferNameSpaceName.setByte(bytesNameSpaceName.length, (byte)0);
		byte[] bytesValueName = valueName.getBytes(StandardCharsets.UTF_8);
		Memory bufferValueName = new Memory(bytesValueName.length + 1);
		bufferValueName.write(0, bytesValueName, 0, bytesValueName.length);
		bufferValueName.setByte(bytesValueName.length, (byte)0);
		byte[] bytesValue = value.getBytes(StandardCharsets.UTF_8);
		Memory bufferValue = new Memory(bytesValue.length + 1);
		bufferValue.write(0, bytesValue, 0, bytesValue.length);
		bufferValue.setByte(bytesValue.length, (byte)0);
		mWrapper.checkError(this, mWrapper.lib3mf_toolpathprofile_setparametervalue.invokeInt(new java.lang.Object[]{mHandle, bufferNameSpaceName, bufferValueName, bufferValue}));
	}

	/**
	 * Sets a profile's base parameter value as double. Fails, if parameter already exists.
	 *
	 * @param nameSpaceName Name of the Parameter Namespace.
	 * @param valueName Value key string.
	 * @param value Double value of the parameter.
	 * @throws Lib3MFException
	 */
	public void setParameterDoubleValue(String nameSpaceName, String valueName, double value) throws Lib3MFException {
		byte[] bytesNameSpaceName = nameSpaceName.getBytes(StandardCharsets.UTF_8);
		Memory bufferNameSpaceName = new Memory(bytesNameSpaceName.length + 1);
		bufferNameSpaceName.write(0, bytesNameSpaceName, 0, bytesNameSpaceName.length);
		bufferNameSpaceName.setByte(bytesNameSpaceName.length, (byte)0);
		byte[] bytesValueName = valueName.getBytes(StandardCharsets.UTF_8);
		Memory bufferValueName = new Memory(bytesValueName.length + 1);
		bufferValueName.write(0, bytesValueName, 0, bytesValueName.length);
		bufferValueName.setByte(bytesValueName.length, (byte)0);
		mWrapper.checkError(this, mWrapper.lib3mf_toolpathprofile_setparameterdoublevalue.invokeInt(new java.lang.Object[]{mHandle, bufferNameSpaceName, bufferValueName, value}));
	}

	/**
	 * Sets a profile's parameter value as integer. Fails, if parameter already exists.
	 *
	 * @param nameSpaceName Name of the Parameter Namespace.
	 * @param valueName Value key string.
	 * @param value Integer value of the parameter.
	 * @throws Lib3MFException
	 */
	public void setParameterIntegerValue(String nameSpaceName, String valueName, long value) throws Lib3MFException {
		byte[] bytesNameSpaceName = nameSpaceName.getBytes(StandardCharsets.UTF_8);
		Memory bufferNameSpaceName = new Memory(bytesNameSpaceName.length + 1);
		bufferNameSpaceName.write(0, bytesNameSpaceName, 0, bytesNameSpaceName.length);
		bufferNameSpaceName.setByte(bytesNameSpaceName.length, (byte)0);
		byte[] bytesValueName = valueName.getBytes(StandardCharsets.UTF_8);
		Memory bufferValueName = new Memory(bytesValueName.length + 1);
		bufferValueName.write(0, bytesValueName, 0, bytesValueName.length);
		bufferValueName.setByte(bytesValueName.length, (byte)0);
		mWrapper.checkError(this, mWrapper.lib3mf_toolpathprofile_setparameterintegervalue.invokeInt(new java.lang.Object[]{mHandle, bufferNameSpaceName, bufferValueName, value}));
	}

	/**
	 * Sets a profile's parameter value as boolean. Fails, if parameter already exists.
	 *
	 * @param nameSpaceName Name of the Parameter Namespace.
	 * @param valueName Value key string.
	 * @param value Boolean value of the parameter.
	 * @throws Lib3MFException
	 */
	public void setParameterBoolValue(String nameSpaceName, String valueName, boolean value) throws Lib3MFException {
		byte[] bytesNameSpaceName = nameSpaceName.getBytes(StandardCharsets.UTF_8);
		Memory bufferNameSpaceName = new Memory(bytesNameSpaceName.length + 1);
		bufferNameSpaceName.write(0, bytesNameSpaceName, 0, bytesNameSpaceName.length);
		bufferNameSpaceName.setByte(bytesNameSpaceName.length, (byte)0);
		byte[] bytesValueName = valueName.getBytes(StandardCharsets.UTF_8);
		Memory bufferValueName = new Memory(bytesValueName.length + 1);
		bufferValueName.write(0, bytesValueName, 0, bytesValueName.length);
		bufferValueName.setByte(bytesValueName.length, (byte)0);
		mWrapper.checkError(this, mWrapper.lib3mf_toolpathprofile_setparameterboolvalue.invokeInt(new java.lang.Object[]{mHandle, bufferNameSpaceName, bufferValueName, value}));
	}

	/**
	 * Removes a parameter, if it exists. Removes any associated modifier that exists.
	 *
	 * @param nameSpaceName Name of the Parameter Namespace.
	 * @param valueName Parameter key string.
	 * @throws Lib3MFException
	 */
	public void removeParameter(String nameSpaceName, String valueName) throws Lib3MFException {
		byte[] bytesNameSpaceName = nameSpaceName.getBytes(StandardCharsets.UTF_8);
		Memory bufferNameSpaceName = new Memory(bytesNameSpaceName.length + 1);
		bufferNameSpaceName.write(0, bytesNameSpaceName, 0, bytesNameSpaceName.length);
		bufferNameSpaceName.setByte(bytesNameSpaceName.length, (byte)0);
		byte[] bytesValueName = valueName.getBytes(StandardCharsets.UTF_8);
		Memory bufferValueName = new Memory(bytesValueName.length + 1);
		bufferValueName.write(0, bytesValueName, 0, bytesValueName.length);
		bufferValueName.setByte(bytesValueName.length, (byte)0);
		mWrapper.checkError(this, mWrapper.lib3mf_toolpathprofile_removeparameter.invokeInt(new java.lang.Object[]{mHandle, bufferNameSpaceName, bufferValueName}));
	}

	/**
	 * Returns the number of modifiers.
	 *
	 * @return Returns the number of modifiers.
	 * @throws Lib3MFException
	 */
	public int getModifierCount() throws Lib3MFException {
		Pointer bufferCount = new Memory(4);
		mWrapper.checkError(this, mWrapper.lib3mf_toolpathprofile_getmodifiercount.invokeInt(new java.lang.Object[]{mHandle, bufferCount}));
		return bufferCount.getInt(0);
	}

	/**
	 * Returns the Name of a modifier by its index.
	 *
	 * @param index Index of modifier (0-based). Call will fail if an invalid index is given.
	 * @return Returns the name of the modifier.
	 * @throws Lib3MFException
	 */
	public String getModifierNameByIndex(int index) throws Lib3MFException {
		Pointer bytesNeededName = new Memory(4);
		mWrapper.checkError(this, mWrapper.lib3mf_toolpathprofile_getmodifiernamebyindex.invokeInt(new java.lang.Object[]{mHandle, index, 0, bytesNeededName, null}));
		int sizeName = bytesNeededName.getInt(0);
		Pointer bufferName = new Memory(sizeName);
		mWrapper.checkError(this, mWrapper.lib3mf_toolpathprofile_getmodifiernamebyindex.invokeInt(new java.lang.Object[]{mHandle, index, sizeName, bytesNeededName, bufferName}));
		return new String(bufferName.getByteArray(0, sizeName - 1), StandardCharsets.UTF_8);
	}

	/**
	 * Returns the type of a modifier by its index.
	 *
	 * @param index Index of modifier (0-based). Call will fail if an invalid index is given.
	 * @return Returns the type of the modifier.
	 * @throws Lib3MFException
	 */
	public Lib3MFWrapper.ToolpathProfileModificationType getModifierTypeByIndex(int index) throws Lib3MFException {
		Pointer bufferModifierType = new Memory(4);
		mWrapper.checkError(this, mWrapper.lib3mf_toolpathprofile_getmodifiertypebyindex.invokeInt(new java.lang.Object[]{mHandle, index, bufferModifierType}));
		return Lib3MFWrapper.EnumConversion.convertConstToToolpathProfileModificationType(bufferModifierType.getInt(0));
	}

	/**
	 * Returns the NameSpace of a modifier by its index.
	 *
	 * @param index Index of modifier (0-based). Call will fail if an invalid index is given.
	 * @return Returns the namespace of the modifier.
	 * @throws Lib3MFException
	 */
	public String getModifierNameSpaceByIndex(int index) throws Lib3MFException {
		Pointer bytesNeededNameSpace = new Memory(4);
		mWrapper.checkError(this, mWrapper.lib3mf_toolpathprofile_getmodifiernamespacebyindex.invokeInt(new java.lang.Object[]{mHandle, index, 0, bytesNeededNameSpace, null}));
		int sizeNameSpace = bytesNeededNameSpace.getInt(0);
		Pointer bufferNameSpace = new Memory(sizeNameSpace);
		mWrapper.checkError(this, mWrapper.lib3mf_toolpathprofile_getmodifiernamespacebyindex.invokeInt(new java.lang.Object[]{mHandle, index, sizeNameSpace, bytesNeededNameSpace, bufferNameSpace}));
		return new String(bufferNameSpace.getByteArray(0, sizeNameSpace - 1), StandardCharsets.UTF_8);
	}

	/**
	 * Checks if a modifier exists.
	 *
	 * @param nameSpaceName Name of the Parameter Namespace.
	 * @param valueName Parameter key string.
	 * @return Returns if a modifier exists.
	 * @throws Lib3MFException
	 */
	public boolean hasModifier(String nameSpaceName, String valueName) throws Lib3MFException {
		byte[] bytesNameSpaceName = nameSpaceName.getBytes(StandardCharsets.UTF_8);
		Memory bufferNameSpaceName = new Memory(bytesNameSpaceName.length + 1);
		bufferNameSpaceName.write(0, bytesNameSpaceName, 0, bytesNameSpaceName.length);
		bufferNameSpaceName.setByte(bytesNameSpaceName.length, (byte)0);
		byte[] bytesValueName = valueName.getBytes(StandardCharsets.UTF_8);
		Memory bufferValueName = new Memory(bytesValueName.length + 1);
		bufferValueName.write(0, bytesValueName, 0, bytesValueName.length);
		bufferValueName.setByte(bytesValueName.length, (byte)0);
		Pointer bufferValueExists = new Memory(1);
		mWrapper.checkError(this, mWrapper.lib3mf_toolpathprofile_hasmodifier.invokeInt(new java.lang.Object[]{mHandle, bufferNameSpaceName, bufferValueName, bufferValueExists}));
		return bufferValueExists.getByte(0) != 0;
	}

	/**
	 * Returns modifier by index.
	 *
	 * @param index Index of modifier (0-based). Call will fail if an invalid index is given.
	 * @return GetModifierInformationByIndex Result Tuple
	 * @throws Lib3MFException
	 */
	public GetModifierInformationByIndexResult getModifierInformationByIndex(int index) throws Lib3MFException {
		Pointer bytesNeededNameSpaceName = new Memory(4);
		Pointer bytesNeededValueName = new Memory(4);
		Pointer bufferModifierType = new Memory(4);
		Pointer bufferModificationFactor = new Memory(4);
		Pointer bufferMinValue = new Memory(8);
		Pointer bufferMaxValue = new Memory(8);
		mWrapper.checkError(this, mWrapper.lib3mf_toolpathprofile_getmodifierinformationbyindex.invokeInt(new java.lang.Object[]{mHandle, index, 0, bytesNeededNameSpaceName, null, 0, bytesNeededValueName, null, bufferModifierType, bufferModificationFactor, bufferMinValue, bufferMaxValue}));
		int sizeNameSpaceName = bytesNeededNameSpaceName.getInt(0);
		Pointer bufferNameSpaceName = new Memory(sizeNameSpaceName);
		int sizeValueName = bytesNeededValueName.getInt(0);
		Pointer bufferValueName = new Memory(sizeValueName);
		mWrapper.checkError(this, mWrapper.lib3mf_toolpathprofile_getmodifierinformationbyindex.invokeInt(new java.lang.Object[]{mHandle, index, sizeNameSpaceName, bytesNeededNameSpaceName, bufferNameSpaceName, sizeValueName, bytesNeededValueName, bufferValueName, bufferModifierType, bufferModificationFactor, bufferMinValue, bufferMaxValue}));
		GetModifierInformationByIndexResult returnTuple = new GetModifierInformationByIndexResult();
		returnTuple.NameSpaceName = new String(bufferNameSpaceName.getByteArray(0, sizeNameSpaceName - 1), StandardCharsets.UTF_8);
		returnTuple.ValueName = new String(bufferValueName.getByteArray(0, sizeValueName - 1), StandardCharsets.UTF_8);
		returnTuple.ModifierType = Lib3MFWrapper.EnumConversion.convertConstToToolpathProfileModificationType(bufferModifierType.getInt(0));
		returnTuple.ModificationFactor = Lib3MFWrapper.EnumConversion.convertConstToToolpathProfileModificationFactor(bufferModificationFactor.getInt(0));
		returnTuple.MinValue = bufferMinValue.getDouble(0);
		returnTuple.MaxValue = bufferMaxValue.getDouble(0);
		return returnTuple;
	}

	public static class GetModifierInformationByIndexResult {
		/**
		 * Name of the Parameter Namespace.
		 */
		public String NameSpaceName;

		/**
		 * Parameter key string.
		 */
		public String ValueName;

		/**
		 * Returns the type of the modifier.
		 */
		public Lib3MFWrapper.ToolpathProfileModificationType ModifierType;

		/**
		 * which type of modification factor to use.
		 */
		public Lib3MFWrapper.ToolpathProfileModificationFactor ModificationFactor;

		/**
		 * Desired Value if Factor is equal 0. The corresponding double parameter value MUST be between MinValue and MaxValue.
		 */
		public double MinValue;

		/**
		 * Desired Value if Factor is equal 1. The corresponding double parameter value MUST be between MinValue and MaxValue.
		 */
		public double MaxValue;

	}
	/**
	 * Returns modifier by name.
	 *
	 * @param nameSpaceName Name of the Parameter Namespace.
	 * @param valueName Parameter key string.
	 * @return GetModifierInformationByName Result Tuple
	 * @throws Lib3MFException
	 */
	public GetModifierInformationByNameResult getModifierInformationByName(String nameSpaceName, String valueName) throws Lib3MFException {
		byte[] bytesNameSpaceName = nameSpaceName.getBytes(StandardCharsets.UTF_8);
		Memory bufferNameSpaceName = new Memory(bytesNameSpaceName.length + 1);
		bufferNameSpaceName.write(0, bytesNameSpaceName, 0, bytesNameSpaceName.length);
		bufferNameSpaceName.setByte(bytesNameSpaceName.length, (byte)0);
		byte[] bytesValueName = valueName.getBytes(StandardCharsets.UTF_8);
		Memory bufferValueName = new Memory(bytesValueName.length + 1);
		bufferValueName.write(0, bytesValueName, 0, bytesValueName.length);
		bufferValueName.setByte(bytesValueName.length, (byte)0);
		Pointer bufferModifierType = new Memory(4);
		Pointer bufferModificationFactor = new Memory(4);
		Pointer bufferMinValue = new Memory(8);
		Pointer bufferMaxValue = new Memory(8);
		mWrapper.checkError(this, mWrapper.lib3mf_toolpathprofile_getmodifierinformationbyname.invokeInt(new java.lang.Object[]{mHandle, bufferNameSpaceName, bufferValueName, bufferModifierType, bufferModificationFactor, bufferMinValue, bufferMaxValue}));
		GetModifierInformationByNameResult returnTuple = new GetModifierInformationByNameResult();
		returnTuple.ModifierType = Lib3MFWrapper.EnumConversion.convertConstToToolpathProfileModificationType(bufferModifierType.getInt(0));
		returnTuple.ModificationFactor = Lib3MFWrapper.EnumConversion.convertConstToToolpathProfileModificationFactor(bufferModificationFactor.getInt(0));
		returnTuple.MinValue = bufferMinValue.getDouble(0);
		returnTuple.MaxValue = bufferMaxValue.getDouble(0);
		return returnTuple;
	}

	public static class GetModifierInformationByNameResult {
		/**
		 * Returns the type of the modifier.
		 */
		public Lib3MFWrapper.ToolpathProfileModificationType ModifierType;

		/**
		 * which type of modification factor to use.
		 */
		public Lib3MFWrapper.ToolpathProfileModificationFactor ModificationFactor;

		/**
		 * Desired Value if Factor is equal 0. The corresponding double parameter value MUST be between MinValue and MaxValue.
		 */
		public double MinValue;

		/**
		 * Desired Value if Factor is equal 1. The corresponding double parameter value MUST be between MinValue and MaxValue.
		 */
		public double MaxValue;

	}
	/**
	 * Adds a new modifier. Fails, should a modifier already exist with the same name. Fails if no Parameter exists with this name/namespace. Fails if the parameter does not have a Double value attached.
	 *
	 * @param nameSpaceName Name of the Parameter Namespace.
	 * @param valueName Parameter key string.
	 * @param modifierType Returns the type of the modifier.
	 * @param modificationFactor which type of modification factor to use.
	 * @param minValue Desired Value if Factor is equal 0. The corresponding double parameter value MUST be between MinValue and MaxValue.
	 * @param maxValue Desired Value if Factor is equal 1. The corresponding double parameter value MUST be between MinValue and MaxValue.
	 * @throws Lib3MFException
	 */
	public void addModifier(String nameSpaceName, String valueName, Lib3MFWrapper.ToolpathProfileModificationType modifierType, Lib3MFWrapper.ToolpathProfileModificationFactor modificationFactor, double minValue, double maxValue) throws Lib3MFException {
		byte[] bytesNameSpaceName = nameSpaceName.getBytes(StandardCharsets.UTF_8);
		Memory bufferNameSpaceName = new Memory(bytesNameSpaceName.length + 1);
		bufferNameSpaceName.write(0, bytesNameSpaceName, 0, bytesNameSpaceName.length);
		bufferNameSpaceName.setByte(bytesNameSpaceName.length, (byte)0);
		byte[] bytesValueName = valueName.getBytes(StandardCharsets.UTF_8);
		Memory bufferValueName = new Memory(bytesValueName.length + 1);
		bufferValueName.write(0, bytesValueName, 0, bytesValueName.length);
		bufferValueName.setByte(bytesValueName.length, (byte)0);
		mWrapper.checkError(this, mWrapper.lib3mf_toolpathprofile_addmodifier.invokeInt(new java.lang.Object[]{mHandle, bufferNameSpaceName, bufferValueName, Lib3MFWrapper.EnumConversion.convertToolpathProfileModificationTypeToConst(modifierType), Lib3MFWrapper.EnumConversion.convertToolpathProfileModificationFactorToConst(modificationFactor), minValue, maxValue}));
	}

	/**
	 * Changes an existing modifier. Fails, should no modifier exist with this name. Fails if no Parameter exists with this name/namespace. Fails if the parameter does not have a Double value attached.
	 *
	 * @param nameSpaceName Name of the Parameter Namespace.
	 * @param valueName Parameter key string.
	 * @param modifierType Returns the type of the modifier.
	 * @param modificationFactor which type of modification factor to use.
	 * @param minValue Desired Value if Factor is equal 0. The corresponding double parameter value MUST be between MinValue and MaxValue.
	 * @param maxValue Desired Value if Factor is equal 1. The corresponding double parameter value MUST be between MinValue and MaxValue.
	 * @throws Lib3MFException
	 */
	public void changeModifier(String nameSpaceName, String valueName, Lib3MFWrapper.ToolpathProfileModificationType modifierType, Lib3MFWrapper.ToolpathProfileModificationFactor modificationFactor, double minValue, double maxValue) throws Lib3MFException {
		byte[] bytesNameSpaceName = nameSpaceName.getBytes(StandardCharsets.UTF_8);
		Memory bufferNameSpaceName = new Memory(bytesNameSpaceName.length + 1);
		bufferNameSpaceName.write(0, bytesNameSpaceName, 0, bytesNameSpaceName.length);
		bufferNameSpaceName.setByte(bytesNameSpaceName.length, (byte)0);
		byte[] bytesValueName = valueName.getBytes(StandardCharsets.UTF_8);
		Memory bufferValueName = new Memory(bytesValueName.length + 1);
		bufferValueName.write(0, bytesValueName, 0, bytesValueName.length);
		bufferValueName.setByte(bytesValueName.length, (byte)0);
		mWrapper.checkError(this, mWrapper.lib3mf_toolpathprofile_changemodifier.invokeInt(new java.lang.Object[]{mHandle, bufferNameSpaceName, bufferValueName, Lib3MFWrapper.EnumConversion.convertToolpathProfileModificationTypeToConst(modifierType), Lib3MFWrapper.EnumConversion.convertToolpathProfileModificationFactorToConst(modificationFactor), minValue, maxValue}));
	}

	/**
	 * Removes a modifier, if it exists.
	 *
	 * @param nameSpaceName Name of the Parameter Namespace.
	 * @param valueName Parameter key string.
	 * @throws Lib3MFException
	 */
	public void removeModifier(String nameSpaceName, String valueName) throws Lib3MFException {
		byte[] bytesNameSpaceName = nameSpaceName.getBytes(StandardCharsets.UTF_8);
		Memory bufferNameSpaceName = new Memory(bytesNameSpaceName.length + 1);
		bufferNameSpaceName.write(0, bytesNameSpaceName, 0, bytesNameSpaceName.length);
		bufferNameSpaceName.setByte(bytesNameSpaceName.length, (byte)0);
		byte[] bytesValueName = valueName.getBytes(StandardCharsets.UTF_8);
		Memory bufferValueName = new Memory(bytesValueName.length + 1);
		bufferValueName.write(0, bytesValueName, 0, bytesValueName.length);
		bufferValueName.setByte(bytesValueName.length, (byte)0);
		mWrapper.checkError(this, mWrapper.lib3mf_toolpathprofile_removemodifier.invokeInt(new java.lang.Object[]{mHandle, bufferNameSpaceName, bufferValueName}));
	}


}

