set basepath=%~dp0
set IDLxmlname=%1
set AutogeneratedBuildPath=%2
"%basepath%bin\act.exe" %IDLxmlname%
set TempHeaderFolder=Lib3MF_component
rmdir /Q /S "%AutogeneratedBuildPath%\Bindings"
rmdir /Q /S "%AutogeneratedBuildPath%\Source\Implementation"
robocopy /E "%TempHeaderFolder%\Bindings" "%AutogeneratedBuildPath%\Bindings" /NFL /NDL /NJH /NJS /nc /ns /np
robocopy /E "%TempHeaderFolder%\Implementations\Cpp\Interfaces" "%AutogeneratedBuildPath%\Source\Implementation" /NFL /NDL /NJH /NJS /nc /ns /np
rmdir /Q /S %TempHeaderFolder%
exit 0