#!/bin/sh

set -euxo pipefail

cd "$(dirname "$0")"

./act.arm.darwin lib3mf.xml # -bindings ../Autogenerated/Bindings -interfaces ../Autogenerated/Source -suppresssubcomponents -suppresslicense -suppressstub -suppressexamples
