name: Integration Test

on:
  workflow_dispatch:

jobs:
  last_release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout latest release
        uses: actions/checkout@v2
        with:
          ref: refs/tags/$(git describe --tags `git rev-list --tags --max-count=1`)

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get latest release info from GitHub API
        id: get_release
        run: |
          LATEST_RELEASE_URL=$(curl -s https://api.github.com/repos/3MFConsortium/test_suites/releases/latest | grep "zipball_url" | cut -d '"' -f 4)
          echo "LATEST_RELEASE_URL=${LATEST_RELEASE_URL}" >> $GITHUB_ENV

      - name: Download latest SDK zip
        run: |
          wget ${{ env.LATEST_RELEASE_URL }} -O latest_release.zip

      - name: Unpack the SDK
        run: |
          unzip latest_release.zip -d lib3mf_sdk

      - name: Build CppDynamic
        run: |
          sh lib3mf_sdk/Examples/CppDynamic/GenerateMake.sh
          cd lib3mf_sdk/Examples/CppDynamic/build
          cmake --build .
          ./Example_ExtractInfo ../../Files/Helix.3mf

      - name: Download and unzip test suite
        run: |
          wget https://github.com/3MFConsortium/test_suites/releases/download/v2.0.0/3MF_Conformance_Test_Suites_v2.0.0.zip
          unzip 3MF_Conformance_Test_Suites_v2.0.0.zip -d test_suites

      - name: Copy integration test script
        run: |
          cp CI/integration_test.py test_suites/3MF_Conformance_Test_Suites_v2.0.0/

      - name: Run integration tests
        run: |
          python test_suites/3MF_Conformance_Test_Suites_v2.0.0/integration_test.py