on: [push, pull_request]
name: Test
jobs:
  test-linux:
    runs-on: ubuntu-18.04
    steps:
      - run: sudo apt install -y valgrind
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: sh cmake/GenerateMake.sh
      - run: cmake --build . --target lib3mf_memcheck
        working-directory: ./build
      - run: ctest -V
        working-directory: ./build
  test-linux-mingw-w64:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y mingw-w64
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: sh cmake/GenerateMinGW.sh
      - run: cmake --build .
        working-directory: ./build
      - run: ctest -V
        working-directory: ./build
  test-macos:
    strategy:
      matrix:
        os: [macos-10.15, macos-11.0]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: sh cmake/GenerateMake.sh
      - run: cmake --build .
        working-directory: ./build
      - run: ctest -V
        working-directory: ./build
  test-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: sh cmake/GenerateVS2019.sh
      - run: cmake --build .
        working-directory: ./build
      - run: ctest -V
        working-directory: ./build

